id: P007133
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 12:43:51.278764
source_metadata:
  id: bdr:W29249
  title: ཉི་དབང་མགོན་པོས་མཛད་པའི་གླུ་ཐལ་སྦྱར་མ།
  author: ''
  volumes:
    1fd1b76e5b6e4d3fba81ed23dffba10b:
      image_group_id: I1KG8526
      title: Volume 1 of nyi dbang mgon pos mdzad pa'i glu thal sbyar ma/
      volume_number: 1
      total_pages: 210
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
