id: P007133
initial_creation_type: ocr
source_metadata:
  id: bdr:W29249
  title: ཉི་དབང་མགོན་པོས་མཛད་པའི་གླུ་ཐལ་སྦྱར་མ།
  author: ''
  volumes:
    54e406b633f147cba399acd7f9bcf24f:
      image_group_id: I1KG8526
      title: ''
      volume_number: 1
      total_pages: 210
ebook_metadata:
  title: ཉི་དབང་མགོན་པོས་མཛད་པའི་གླུ་ཐལ་སྦྱར་མ།
  author: ''
  sku: P007133
  cover: cover.jpg
  layers:
  - pagination
