id: IA26BA222
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:24:29+00:00'
last_modified: '2022-06-09T06:20:45.114277+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29249
  title: ཉི་དབང་མགོན་པོས་མཛད་པའི་གླུ་ཐལ་སྦྱར་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5FF4:
      image_group_id: I1KG8526
      title: Volume 1 of nyi dbang mgon pos mdzad pa'i glu thal sbyar ma/
      total_pages: 210
      order: 1
      base_file: 5FF4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
