id: IA26BA222
legacy_id: P007133
ocr_import_info:
  bdrc_scan_id: W29249
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T00:23:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T10:19:29.932495+00:00'
last_modified: 2022-09-02 18:19:44.690407
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29249
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29249
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཉི་དབང་མགོན་པོས་མཛད་པའི་གླུ་ཐལ་སྦྱར་མ།
  author: དངོས་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.8864179951444312
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG8526:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8526
      total_pages: 210
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8526.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8864179951444312
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
